name       : nicotine-plus
version    : 3.0.2
release    : 8
source     :
    - https://github.com/Nicotine-Plus/nicotine-plus/archive/refs/tags/3.0.2.tar.gz : a2a50a442e1dee035aa5825ef7b590c1c457bddba17e5a4abe6466113f5a4af1
license    : GPL-3.0-or-later
component  : network.download
summary    : A graphical client for the SoulSeek peer-to-peer system
description: |
    A graphical client for the SoulSeek peer-to-peer system
builddeps  :
    - python-pytest   # Tests
rundeps    :
    - libappindicator
    - python-gobject
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    find $installdir \
        -name "README*" -prune -exec rm -r '{}' + \
        -or -iname "license*" -prune -exec rm -r '{}' +
check      : |
    cd nicotine-plus-$version
    # Skip a test that requires network.
    python3 -m pytest -k 'not version'
