name       : nicotine-plus
version    : 3.2.2
release    : 12
source     :
    - https://github.com/nicotine-plus/nicotine-plus/archive/refs/tags/3.2.2.tar.gz : f58286f4dec6febfeab075cdfe2d2fc35c58349a504f7d393ec129df132ad40f
license    : GPL-3.0-or-later
component  : network.download
summary    : A graphical client for the SoulSeek peer-to-peer system
description: |
    A graphical client for the SoulSeek peer-to-peer system
builddeps  :
    - python-pytest # Tests.
rundeps    :
    - libayatana-appindicator
    - libgtk-3
    - python-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    find $installdir \
        -name "README*" -prune -exec rm -r '{}' + \
        -or -iname "license*" -prune -exec rm -r '{}' +
check      : |
    cd nicotine-plus-$version
    # Skip the startup test which requires a desktop environment.
    python3 -m pytest -k 'not startup'
