name       : nicotine-plus
version    : 2.1.2
release    : 5
source     :
    - https://github.com/Nicotine-Plus/nicotine-plus/archive/2.1.2.tar.gz : 3ed18ade97183c632836eb8e304a515fc19a35babb46cc6e6747bcfd8205dcdf
license    : GPL-3.0-or-later
component  : network.download
summary    : A graphical client for the SoulSeek peer-to-peer system
description: |
    A graphical client for the SoulSeek peer-to-peer system
builddeps  :
    - python-pytaglib # Tests
    - python-pytest   # Tests
rundeps    :
    - libnotify
    - mutagen
    - python-gobject
    - python-pytaglib
    - python3-dbus
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    find $installdir \
        -name "README*" -prune -exec rm -r '{}' + \
        -or -iname "license*" -prune -exec rm -r '{}' +
check      : |
    cd nicotine-plus-$version
    # Skip a test that requires network.
    python3 -m pytest -k 'not version'
