name       : nicotine-plus
version    : 2.0.1
release    : 3
source     :
    - https://github.com/Nicotine-Plus/nicotine-plus/archive/2.0.1.tar.gz : 229acf6e287e1c3ae7d07b04b85230c3fa2edc0c17298583e2f13dd986bbda5a
license    : GPL-3.0-or-later
component  : network.download
summary    : A graphical client for the SoulSeek peer-to-peer system
description: |
    A graphical client for the SoulSeek peer-to-peer system
builddeps  :
    - python-pytest
rundeps    :
    - libnotify
    - mutagen
    - python-gobject
    - python3-dbus
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    find $installdir \
        -name "README*" -prune -exec rm -r '{}' + \
        -or -iname "license*" -prune -exec rm -r '{}' +
check      : |
    cd nicotine-plus-$version
    py.test3
