name       : nicotine-plus
version    : 3.2.7
release    : 14
source     :
    - https://github.com/nicotine-plus/nicotine-plus/archive/refs/tags/3.2.7.tar.gz : 575b56e17624d326be32b73b5ab4670967bf3cef3d7d02b1de8d07b950946cc7
license    : GPL-3.0-or-later
component  : network.download
summary    : A graphical client for the SoulSeek peer-to-peer system
description: |
    A graphical client for the SoulSeek peer-to-peer system
builddeps  :
    - python-pytest # Tests.
rundeps    :
    - libayatana-appindicator
    - libgtk-3
    - python-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
    find $installdir \
        -name "README*" -prune -exec rm -r '{}' + \
        -or -iname "license*" -prune -exec rm -r '{}' +
check      : |
    cd nicotine-plus-$version
    # Skip the startup test which requires a desktop environment.
    python3 -m pytest -k 'not startup'
