name       : nicotine-plus
version    : 1.4.1
release    : 2
source     :
    - https://github.com/Nicotine-Plus/nicotine-plus/archive/1.4.1.tar.gz : 1b38ef196d981e4eb96fa990cc463143289784f988f559c4400b1d461497b7d6
license    : GPL-3.0
component  : network.download
summary    : A graphical client for the SoulSeek peer-to-peer system
description: |
    A graphical client for the SoulSeek peer-to-peer system
builddeps  :
    - pkgconfig(pygtk-2.0)
    - mutagen
rundeps    :
    - python-gtk2
install    : |
    %python_install
